#! /bin/sh

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=start.pl
SERVICE=timer
DIRECTORY=/home/andreas/SignalBot/
NAME=signalBotTimer
DESC="signalBotTimer check stuff like is a event starting"

test -f $DIRECTORY$DAEMON || exit 0

set -e

case "$1" in
  start)
 echo -n "Starting $DESC: "
 start-stop-daemon --start --quiet -c andreas --chdir $DIRECTORY --pidfile $DIRECTORY.$NAME.pid \
  --exec /usr/bin/perl --startas $DIRECTORY$DAEMON SERVICE
 echo "$NAME."
 ;;
  stop)
 echo -n "Stopping $DESC: "
 # --quiet
 start-stop-daemon --stop --signal 15 -u andreas --pidfile $DIRECTORY.$NAME.pid
 echo "$NAME."
 ;;
  restart|force-reload)
 echo -n "Restarting $DESC: "
 start-stop-daemon --stop --quiet -u andreas --pidfile $DIRECTORY.$NAME.pid
 sleep 1
 start-stop-daemon --start --quiet -c andreas --chdir $DIRECTORY --pidfile $DIRECTORY.$NAME.pid \
  --exec /usr/bin/perl --startas $DIRECTORY$DAEMON SERVICE
 echo "$NAME."
 ;;
  *)
 N=/etc/init.d/$NAME
 # echo "Usage: $N {start|stop|restart|reload|force-reload}" >&2
 echo "Usage: $N {start|stop|restart|force-reload}" >&2
 exit 1
 ;;
esac

exit 0