#! /bin/sh

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=SignalBot.pl
DIRECTORY=/home/andreas/SignalBot/
NAME=signalBot
DESC="signalBot um dinge im chat zu automatisieren"

test -f $DIRECTORY$DAEMON || exit 0

set -e

case "$1" in
  start)
 echo -n "Starting $DESC: "
 start-stop-daemon --start --quiet -c andreas --chdir $DIRECTORY --pidfile $DIRECTORY.$NAME.pid \
  --exec /usr/bin/perl --startas $DIRECTORY$DAEMON
 echo "$NAME."
 ;;
  stop)
 echo -n "Stopping $DESC: "
 # --quiet
 start-stop-daemon --stop --signal 15 -u andreas --chdir $DIRECTORY --pidfile $DIRECTORY.$NAME.pid \
  --exec /usr/bin/perl --startas $DIRECTORY.DAEMON
 echo "$NAME."
 ;;
  restart|force-reload)
 echo -n "Restarting $DESC: "
 start-stop-daemon --stop --quiet -u andreas --chdir $DIRECTORY --pidfile \
  $DIRECTORY.$NAME.pid --exec /usr/bin/perl --startas $DIRECTORY$DAEMON
 sleep 1
 start-stop-daemon --start --quiet -c andreas --chdir $DIRECTORY --pidfile \
  $DIRECTORY.$NAME.pid --exec /usr/bin/perl --startas $DIRECTORY$DAEMON
 echo "$NAME."
 ;;
  *)
 N=/etc/init.d/$NAME
 # echo "Usage: $N {start|stop|restart|reload|force-reload}" >&2
 echo "Usage: $N {start|stop|restart|force-reload}" >&2
 exit 1
 ;;
esac

exit 0